table DimFundraisingEvent
	lineageTag: 752b4458-a280-4b83-b630-80340b8ed076

	column FundraisingEventKey
		dataType: int64
		formatString: 0
		lineageTag: e2f65d2b-c027-4813-91be-fe4c99c11085
		summarizeBy: none
		sourceColumn: FundraisingEventKey

		annotation SummarizationSetBy = Automatic

	column FundraisingEventID
		dataType: int64
		formatString: 0
		lineageTag: 34ec768d-eb1d-476a-9b5a-16021a520bc0
		summarizeBy: none
		sourceColumn: FundraisingEventID

		annotation SummarizationSetBy = Automatic

	column EventName
		dataType: string
		lineageTag: 8c7eb7e2-2c5f-4cf8-b07a-83ac810bd537
		summarizeBy: none
		sourceColumn: EventName

		annotation SummarizationSetBy = Automatic

	column EventDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ce006926-c96e-48de-8757-00ad9e621dbd
		summarizeBy: none
		sourceColumn: EventDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Location
		dataType: string
		lineageTag: b005c337-2b6a-41ba-a7f7-d716ee34664d
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column TargetAmount
		dataType: double
		lineageTag: 0cde05b4-bf2d-4c5f-a690-997458051e9f
		summarizeBy: none
		sourceColumn: TargetAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsGeneralFund
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 217b3a74-a23e-42ce-a70a-f69a3e7e12aa
		summarizeBy: none
		sourceColumn: IsGeneralFund

		annotation SummarizationSetBy = Automatic

	partition DimFundraisingEvent = m
		mode: import
		source =
				let
				    Source = Sql.Database("PETRISLAP2025\PETRIS2022", "Serenity1"),
				    dw_DimFundraisingEvent = Source{[Schema="dw",Item="DimFundraisingEvent"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dw_DimFundraisingEvent,{{"IsGeneralFund", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

