table DimDate
	lineageTag: 6d124f59-1931-415e-bd7b-efd5219881cf

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 01d07635-fbff-4488-b707-be5a3205782f
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column FullDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 222018dc-9fb0-46ed-bcf5-d1cf7d2ccdd9
		summarizeBy: none
		sourceColumn: FullDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c92e7d8e-90dc-4701-9e30-46583d335384
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 2d425f1a-af88-496f-9bb6-34638e60d9b4
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 27a8fe64-d9a0-43c3-a010-5c32ce499a3c
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 8dcfd317-c376-4822-8abd-bda2ac2c8a3b
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: c1e308dc-b417-417d-9756-7d4371d0099e
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 10266c6b-e8f0-4d4e-a5a4-6224748e9eb5
		summarizeBy: sum
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column 'Month Year' = FORMAT(DimDate[FullDate], "MMM YYYY")
		lineageTag: ea713367-4137-43d4-ace5-1f64c40b3f0f
		summarizeBy: none
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month' =
			
			FORMAT ( DimDate[FullDate], "yyyy MMM" )
		lineageTag: f1769712-9296-4f9d-9c59-8ccbaf9990e9
		summarizeBy: none
		sortByColumn: MonthSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthSort =
			
			FORMAT ( DimDate[FullDate], "yyyymm" )
		lineageTag: 90e82427-617c-4164-9934-46e6cbca2980
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT(DimDate[FullDate], "MMM")
		lineageTag: cff278ed-b1b4-4a37-a68e-dd77a3ee0d6b
		summarizeBy: none
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	hierarchy 'Year Hierarchy'
		lineageTag: 9fe9a20f-54a6-4568-9977-ed7338062d6d

		level Year
			lineageTag: 8838bf46-6fc7-4930-b2e2-9d09d3c39340
			column: Year

		level 'Month Name'
			lineageTag: ea7cecfe-60ef-4882-bb85-65ae985a0e11
			column: 'Month Name'

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Sql.Database("PETRISLAP2025\PETRIS2022", "Serenity1"),
				    dw_DimDate = Source{[Schema="dw",Item="DimDate"]}[Data],
				    #"Duplicated Column" = Table.DuplicateColumn(dw_DimDate, "FullDate", "FullDate - Copy"),
				    #"Inserted Month" = Table.AddColumn(#"Duplicated Column", "Month.1", each Date.Month([#"FullDate - Copy"]), Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Month",{"Month.1", "FullDate - Copy"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

